### ISSUE TITLE
Provide basic not found view

### ISSUE THREAD

**Issue by davidemoro** [Kotti/Kotti#459]
What do you think about providing by default a simple but nice not found view for Kotti instead of the standard NotFound white page?
I'd like to hear your opinion

**Comment by davidemoro** [comment]
If you register a simple not found view that fills the content slot provided by the default kotti base template:
```
@notfound_view_config(
    renderer='your_package:templates/not_found.pt',
    )
def notfound_view(request):
    request.response.status = '404 Not Found'
    return {}
```

you'll get one error due to the following problems:
* `${request.resource_url(context)}` (see https://github.com/Kotti/Kotti/blob/master/kotti/templates/edit/master.pt#L26) 
* `get_user(self)` (see https://github.com/Kotti/Kotti/blob/master/kotti/request.py#L30)

The previous errors could be avoided for example putting a ``tal:condition="context/__name__|nothing"`` on the ``master.pt`` or returning ``None`` if the context is not found on the ``request.py`` module.

I'll have a look on this issue on a separate branch.

**Comment by disko** [comment]
On 26 Sep 2015, at 11:41, Davide Moro wrote:

> What do you think about providing by default a simple but nice not 
> found view for Kotti instead of the standard NotFound white page?

Yes, please!  :)

**Comment by disko** [comment]
On 26 Sep 2015, at 12:36, Davide Moro wrote:

> * `${request.resource_url(context)}` (see 
> https://github.com/Kotti/Kotti/blob/master/kotti/templates/edit/master.pt#L26)

Just put a ``tal:condition="context | None"`` on the script tag?

> * `get_user(self)` (see 
> https://github.com/Kotti/Kotti/blob/master/kotti/request.py#L30)

I don't see how this is problematic.  Could you please elaborate a bit 
on this?

**Comment by davidemoro** [comment]
Hi @disko!

* ``tal:condition="context | None"`` is not enough because the context is defined (``NotFound``). Since the error is no ``__name__`` attribute I've added a ``context/__name__|nothing``
* ``security.py``: you are right, no issues

**Comment by mgrbyte** [comment]
I've just implemented notfound views in a project and ran into the same error as #187 (The sqlalchemy' `DetatchedInstanceError`), due to the base template I was using for exception views testing `request.user`, which in turn calls `kotti.security.get_user` which raises the error.

This is reproducible when `pyramid.debug_all` or `pyramid.debug_notfound` are false.
When `pyramid.debug_notfound` is true, this error does not happen.

This was observed with Kotti 1.1.5 and Pyramid 1.5.7.

I'm not sure why *exactly* this happens, but here is the most relevant observation:

 * when `pyramid.debug_notfound = true`.
   I edited the [pyrmaid router code](https://github.com/Pylons/pyramid/blob/c59784ba29598170207646a8d54fdc020e0ab5b0/pyramid/router.py#L153) to experiment with why this flag stops/causes the error, I discovered that it is the fact that `context` is "touched" before raising the `HTTPNotFound` error that stops the `DetachedInstanceError`  being raised in a subsequent subrequest (excview_tween that invokes the notfound view in a sub-request) 

I not that this code in `pyramid.router` has changed under Pyramid 1.6, I'll see if I can test it with that.

**Comment by mgrbyte** [comment]
I should note, that I was rolling a staging deployment, and had configured `pyramid.debug_notfound` set to false because I thought that was the "correct" thing to do. 

Leaving it as `true` isn't an issue, and is in fact what I ended up doing to work around the issue, since, apart from the desired side effect (touching the `context` variable before invoking the `notfound` view,  the only other operation that happens is a call to `logging.debug`.

**Comment by davidemoro** [comment]
Hi @mgrbyte,

you discovered how to reproduce the problem, good :)
This should fix the get_user issue (``DetachedInstanceError``):
```
 @request_cache(lambda request: None)
 def get_user(request):
     userid = request.authenticated_userid
-    return get_principals().get(userid)
+    if userid is not None:
+        return get_principals().get(userid)
+    return None
```

By the way, here you can have a look at my branch (tests broken, just for the sake of share my temp work):
* https://github.com/davidemoro/Kotti/tree/notfound

**Comment by mgrbyte** [comment]
@davidemoro The example patch you provide doesn't fix it in the case I described; this is another code path that triggers the same I error; 
When `request.authenticated_user` property is accessed, that triggers the ``kotti.security.list_groups_ext` function via pyamid's `CallbackAuthenticationPolicy`, which does lead to the same error as with `get_user`.

**Comment by mgrbyte** [comment]
In theory, any exception view (notfound view is just one case) that touches an sqlalchemy backed model (at all) is enough to trigger the `DetchaedInstanceError` when the router in pyramid does not touch `context` (i.e a SQLAlchemy orm object) before raising the exception. 
It seems that `HTTPNotFound` is the only exception pyramid's router raising itself, so it might be just limited to this in reality.  I imagine something similar would happen if you registered a exc tween for PredicateMismatch.

**Comment by davidemoro** [comment]
Hi @mgrbyte,

I tried to reproduce your issue with various combinations of ``debug_*`` using my branch forked from the master but it didn't worked for me.
Can you share with me your ``development.ini`` file please?

**Comment by mgrbyte** [comment]
hi @davidemoro 
I've forked from master, and based on the changes in your branch done the same thing.
In order to reproduce I've:

 * Created a new virtualenv
 * Installed Kotti into it w/ python setup.py dev [Had to bump setuptools >= 17.1 using pip)

https://github.com/mgrbyte/Kotti

This will render the not found view with `debug_notfound = true`, and raise `DetachedInstanceError` when `debug_notfound = false`.

**Comment by mgrbyte** [comment]
@davidemoro Can confirm this happens with `pyramid==1.6a2` also.

**Comment by mgrbyte** [comment]
@davidemoro Potential fix:
https://github.com/mgrbyte/Kotti/tree/potential-debug_found-detachedinstanceerror-fix

**Comment by mgrbyte** [comment]
I think the key to fixing this is not have `kotti.security.get_user` use `unauthenticated_userid` instead of `authenticated_userid`. 
The latter will always lookup the user in the database.  I note there is cache on the get_user method,
perhaps this needs more thought about possible interactions; however I think that any code that calls get_user() should already have gone through the authpolicy, thus making this change 'safe'.

@disko, @davidemoro  any concerns if this change was made?

**Comment by davidemoro** [comment]
A couple of comments for @mgrbyte : 
* wrong 404 status (see https://github.com/Kotti/Kotti/compare/master...mgrbyte:potential-debug_found-detachedinstanceerror-fix?expand=1#diff-9d38ef0381ee595fd7105690abbafb99R6)
* i18n, don't forget to run the i18n helper

Regarding your answer I'd like to know the @disko opinion.

**Comment by mgrbyte** [comment]
https://github.com/Kotti/Kotti/compare/master...mgrbyte:master#diff-9d38ef0381ee595fd7105690abbafb99R6

The purpose of the branch is to demonstrate the issue with `DetachedInstanceError` with `debug_notfound`, so probably the i18n stuff doesn't matter in this case?

**Comment by disko** [comment]
> I think the key to fixing this is not have kotti.security.get_user use unauthenticated_userid instead of authenticated_userid. 
> The latter will always lookup the user in the database. I note there is cache on the get_user method,
perhaps this needs more thought about possible interactions; however I think that any code that calls get_user() should already have gone through the authpolicy, thus making this change 'safe'.

I don't know whether this conflicts with the registered ``list_groups_callback``. @dnouri ?

**Comment by dnouri** [comment]
@disko Have any hint for me as to why you think this change could conflict with `list_groups_callback`?

**Comment by disko** [comment]
@dnouri: sorry for the noise – I obviously didn't read the diff properly.  You're right (of course), should be completely unrelated.

@mgrbyte, @davidemoro: looks good, please go ahead and make it a proper PR.  Regarding the status code: it must be 404 for the notfound_view (not sure, I was able to follow your discussion on that topic).

**Comment by mgrbyte** [comment]
@disko @davidemoro I'd be happy to work on this.
 Regarding setting the 404 status, totally agree now (I had a moment, my head was on wrong) :full_moon:

**Comment by disko** [comment]
Implemented in #462.
